<div class="ui hidden divider"></div>

<div class="ui column doubling grid container">
    <div class="column">

        <h3 class="ui dividing header">     
            Política de Privacidade do usuário do PIP OnLine (em vigor desde 04 de maio de 2018) </h3>

        <h4 class="ui dividing header"><a name="p1">1. Escopo e consentimento</a></h4>
        <div class="ui tertiary segment">
            <p>Esta Pol&iacute;tica de Privacidade descreve as pr&aacute;ticas do Procure Im&oacute;veis Paid&eacute;gua. ("PIP", "PIP Online" ou "N&oacute;s"), em rela&ccedil;&atilde;o a dados coletados por meio do nosso website www.pipbeta.com.br, em que qualquer pessoa com mais de 18 anos de idade, ou abaixo desta idade necessariamente autorizada por seu representante legal ("Usu&aacute;rio" ou "Voc&ecirc;") podem se envolver com atividades como criar uma conta, publicar ou visualizar an&uacute;ncios online, trocar mensagens diretas e executar uma s&eacute;rie de fun&ccedil;&otilde;es integradas ("Servi&ccedil;os"). <br />Esta pol&iacute;tica se aplica aos dados que identificam os nossos Usu&aacute;rios individualmente (Dados Pessoais) e demais dados fornecidos pelos Usu&aacute;rios ou coletados durante a utiliza&ccedil;&atilde;o dos Sites (coletivamente denominados "Dados do Usu&aacute;rio"). <br />Em todos os casos, cumpriremos com toda legisla&ccedil;&atilde;o aplic&aacute;vel &agrave; prote&ccedil;&atilde;o de dados nas jurisdi&ccedil;&otilde;es em que operamos. <br />Esta Pol&iacute;tica de Privacidade se sujeita &agrave;s leis brasileiras.<br />A utiliza&ccedil;&atilde;o do site e/ou uso de quaisquer servi&ccedil;os significar&atilde;o que Voc&ecirc; leu, entendeu e consentiu com esta Pol&iacute;tica de Privacidade e com os termos de uso.<br />Voc&ecirc; deve estar ciente de que o Site poder&aacute; eventualmente conter links para sites de terceiros e que ao acess&aacute;-los, Voc&ecirc; pode ser direcionado para p&aacute;ginas de outras empresas fora do nosso ambiente de hospedagem, onde as informa&ccedil;&otilde;es coletadas est&atilde;o fora do nosso controle direto. <br />A pol&iacute;tica de privacidade de propriedade ou aplicativos de terceiros regular&aacute; a informa&ccedil;&atilde;o obtida por estes terceiros sobre Voc&ecirc; nessas situa&ccedil;&otilde;es, cabendo ao Usu&aacute;rio verificar tais pol&iacute;ticas antes da utiliza&ccedil;&atilde;o de referidos sites.</p>
        </div>
        <h4 class="ui dividing header"><a name="p2">2. Informações que coletamos, recebemos e armazenamos</a></h4>
        <div class="ui tertiary segment">
            <p>2.1. Consentimento<br /> A utiliza&ccedil;&atilde;o do Site implica no consentimento do Usu&aacute;rio para coleta, armazenamento e uso das informa&ccedil;&otilde;es pessoais fornecidas e suas atualiza&ccedil;&otilde;es, dados de tr&aacute;fego, endere&ccedil;os IP, entre outros. O Usu&aacute;rio desde j&aacute; autoriza o PIP Online a, a seu crit&eacute;rio, preservar, armazenar todos os an&uacute;ncios e/ou conte&uacute;dos submetidos ao site, bem como todos os seus dados pessoais e demais informa&ccedil;&otilde;es fornecidas e/ou coletadas.</p>
            <p>2.2 Informa&ccedil;&otilde;es da conta:<br /> Quando usu&aacute;rios criam contas em Nosso site informa&ccedil;&otilde;es pessoais s&atilde;o requisitadas, tais como endere&ccedil;o de e-mail, nome completo, CPF ou CNPJ, n&uacute;meros de telefone para contato, fotos que desejem publicar, cria&ccedil;&atilde;o de nomes de usu&aacute;rio e senhas de acesso. Em caso de pessoa juridica, adicionalmente, &eacute; solicitado o nome da empresa e raz&atilde;o social.<br /> Estas informa&ccedil;&otilde;es s&atilde;o requeridas para viabilizar e melhorar o Servi&ccedil;o que prestamos aos Usu&aacute;rios e para obedecer aos Nossos Termos de Uso.</p>
            <p>2.3 Disponibilidade das informa&ccedil;&otilde;es:<br /> Qualquer informa&ccedil;&atilde;o que Usu&aacute;rios disponibilizarem em perfis publicamente dispon&iacute;veis &eacute; de sua pr&oacute;pria responsabilidade. Por esse motivo, Voc&ecirc; deve cuidadosamente considerar os riscos de fazer certas declara&ccedil;&otilde;es ou publicar informa&ccedil;&otilde;es pessoais - especialmente informa&ccedil;&otilde;es como endere&ccedil;o ou localiza&ccedil;&atilde;o precisa. Um Usu&aacute;rio pode copiar/fotografar suas mensagens e circular entre outros Usu&aacute;rios ou fora do Site. N&oacute;s n&atilde;o assumimos qualquer responsabilidade por mensagens ou atos de terceiros que ocorram em decorr&ecirc;ncia da informa&ccedil;&atilde;o que Voc&ecirc; tornou publicamente dispon&iacute;vel a terceiro ou que Voc&ecirc; compartilhou com qualquer pessoa ou com outro Usu&aacute;rio.</p>
            <p>2.4 Ferramentas de pesquisa:<br /> Ao publicar um an&uacute;ncio no PIP Onine, o Usu&aacute;rio compreende que os an&uacute;ncios e o conte&uacute;do poder&atilde;o ser publicamente acess&iacute;veis a terceiros, podendo ser listados como resultados de ferramentas de pesquisa como Google, Yahoo!, Bing, entre outros e no cache destas ferramentas de pesquisa. O Usu&aacute;rio compreende que &eacute; de responsabilidade de cada uma destas ferramentas de pesquisa, websites ou recursos RSS manter seus &iacute;ndices e cache atualizados e remover o Conte&uacute;do de seus &iacute;ndices e cache, pois n&atilde;o temos influ&ecirc;ncia sobre eles.</p>
            <p>2.5 An&uacute;ncios e Transa&ccedil;&otilde;es:<br /> N&oacute;s podemos armazenar e transmitir Sua informa&ccedil;&atilde;o aos nossos parceiros comerciais e afiliados, incluindo informa&ccedil;&atilde;o pessoal e informa&ccedil;&otilde;es de contato. Qualquer informa&ccedil;&atilde;o que os Usu&aacute;rios compartilharem em an&uacute;ncios &eacute; de sua pr&oacute;pria responsabilidade. Assim como com as contas, os Usu&aacute;rios devem considerar com cautela os riscos de deixar certas informa&ccedil;&otilde;es - especialmente informa&ccedil;&otilde;es pessoais, tais como endere&ccedil;o publicamente dispon&iacute;veis em um an&uacute;ncio.</p>
            <p>2.6 Processamento de pagamentos:<br /> O PIP Online utiliza a ferramenta PAGSEGURO para gerenciamento de pagamentos on line. O usu&aacute;rio deve estar ciente de que tais empresas poder&atilde;o coletar e armazenar informa&ccedil;&otilde;es e Dados do Usu&aacute;rio. Os dados que eles coletam est&atilde;o sujeitos &agrave; pol&iacute;tica de privacidade aplic&aacute;vel a esses terceiros e N&oacute;s recomendamos que voc&ecirc; leia tais pol&iacute;ticas de privacidade desse terceiro antes de usar nossos Servi&ccedil;os e aceitar essa Pol&iacute;tica de Privacidade. Clique aqui para acessar a politica de privacidade do Google Analytics. O PIP Online n&atilde;o processa pagamentos diretamente e n&atilde;o armazena informa&ccedil;&otilde;es de cart&otilde;es de cr&eacute;dito dos Usu&aacute;rios. </p>
            <p>2.7 Atendimento ao cliente:<br /> Quando Voc&ecirc; entrar em contato conosco, N&oacute;s podemos coletar as informa&ccedil;&otilde;es pessoais necess&aacute;rias para preencher Sua solicita&ccedil;&atilde;o e para contat&aacute;-lo caso um acompanhamento seja necess&aacute;rio. N&oacute;s tamb&eacute;m podemos contat&aacute;-lo utilizando as informa&ccedil;&otilde;es de contato da sua conta que Voc&ecirc; houver fornecido.</p>
            <p>2.8 Site e dados de dispositivos m&oacute;veis:<br /> N&oacute;s podemos automaticamente receber e registrar informa&ccedil;&atilde;o em nossos servidores de Seu navegador ou dispositivo, incluindo seu endere&ccedil;o IP, atributos de software e hardware, identificadores de dispositivos m&oacute;veis, informa&ccedil;&atilde;o sobre uso de aplicativo, e outras informa&ccedil;&otilde;es de dispositivo e sistema.</p>
            <p>2.9 Contatos:<br /> O Usu&aacute;rio est&aacute; ciente de que o uso dos Sites, independentemente da realiza&ccedil;&atilde;o de cadastro no site, implica na aceita&ccedil;&atilde;o aos Termos de Uso aplic&aacute;veis e a esta Pol&iacute;tica, bem como que o PIP Online poder&aacute; enviar ao Usu&aacute;rio notifica&ccedil;&otilde;es e e-mails sobre an&uacute;ncios promo&ccedil;&otilde;es e conte&uacute;dos especiais. Para n&atilde;o receber tais mensagens, o Usu&aacute;rio dever&aacute; proceder de acordo com as instru&ccedil;&otilde;es de opt-out constante destas.</p>
        </div>
        <h4 class="ui dividing header"><a name="p3">3. Endere&ccedil;o IP, cookies e identificadores de dispositivos m&oacute;veis</a></h4>
        <div class="ui tertiary segment">
            <p>Seu endere&ccedil;o IP e outros dados relativos &agrave; sua conex&atilde;o poder&atilde;o ser utilizados para personalizar o servi&ccedil;o e compreender como os Usu&aacute;rios utilizam o Site.<br /> &Eacute; reservado ao PIP Online bloquear o acesso ao Site de Usu&aacute;rios alocados em alguns pa&iacute;ses, identificados de acordo com o IP utilizado.<br /> N&oacute;s podemos coletar certas informa&ccedil;&otilde;es por meio de tecnologias como tags, cookies e armazenamento local (como seu browser ou dispositivo), que poder&atilde;o ser utilizadas nos Sites, independentemente de cadastro do Usu&aacute;rio. Tags s&atilde;o ferramentas utilizadas para aferi&ccedil;&atilde;o de cliques em determinadas se&ccedil;&otilde;es e links espec&iacute;ficos dos Sites. Cookies s&atilde;o pequenos arquivos de texto que armazenam informa&ccedil;&atilde;o no seu computador, celular ou outro dispositivo local. <br /> Com ajuda dos cookies, o servidor de internet pode salvar, por exemplo, prefer&ecirc;ncias e configura&ccedil;&otilde;es no computador, celular ou outro dispositivo do usu&aacute;rio, as quais s&atilde;o automaticamente restauradas na pr&oacute;xima visita. Ou, para colocar a quest&atilde;o em outros termos, os cookies s&atilde;o usados, entre outras coisas, para tornar o uso do site mais amig&aacute;vel, para que, por exemplo, Voc&ecirc; n&atilde;o tenha que repetir processos de login quando visitar-nos novamente. N&oacute;s usamos tanto cookies persistentes quanto cookies de sess&atilde;o. Enquanto cookies persistentes continuam no seu computador por um per&iacute;odo mais longo de tempo, cookies de sess&atilde;o s&atilde;o automaticamente deletados quando a janela do seu navegador for fechada.<br /> N&oacute;s podemos permitir que terceiros, tais como prestadores de servi&ccedil;o de publicidade e estat&iacute;stica, coletem informa&ccedil;&otilde;es utilizando esse tipo de tecnologia diretamente em nossos Sites. Os dados que eles coletam est&atilde;o sujeitos &agrave; pol&iacute;tica de privacidade aplic&aacute;vel a esses terceiros e N&oacute;s recomendamos que voc&ecirc; leia tais pol&iacute;ticas de privacidade desse terceiro antes de usar nossos Servi&ccedil;os e aceitar essa Pol&iacute;tica de Privacidade. Clique aqui para acessar a politica de privacidade do Google Analytics.</p>
        </div>
        <h4 class="ui dividing header"><a name="p4">4. Uso da informa&ccedil;&atilde;o</a></h4>
        <div class="ui tertiary segment">
            <p>Para prestar Nosso servi&ccedil;o &eacute; poss&iacute;vel que N&oacute;s utilizemos a informa&ccedil;&otilde;es que coletamos e armazenamos, incluindo Dados do Usu&aacute;rio, para os prop&oacute;sitos gerais que seguem:
            <ul class="ui list">
                <li style="color:#000">Para prover servi&ccedil;os ao cliente, incluindo criar e gerenciar contas de Usu&aacute;rios, resolver dificuldades t&eacute;cnicas e habilitar ou desabilitar funcionalidades;</li>
                <li style="color:#000">Para customizar ofertas e experi&ecirc;ncias;</li>
                <li style="color:#000">Para acompanhar a atividade geral e individual do Usu&aacute;rio, tais como buscas por palavra-chave, postagens e transa&ccedil;&otilde;es, e para gerenciar tr&aacute;fego nos Sites;</li>
                <li style="color:#000">Para empreender iniciativas de pesquisa e realizar an&aacute;lises para melhorar os nossos servi&ccedil;os; e</li>
                <li style="color:#000">Para fazer valer nossos Termos de Uso, incluindo o combate &agrave; fraude e a quaisquer il&iacute;citos.</li>
            </ul>
            <p>Respeitadas as disposi&ccedil;&otilde;es legais aplic&aacute;veis, o Usu&aacute;rio autoriza o PIP Online a informar e/ou divulgar seus dados fornecidos e/ ou coletados em caso de exig&ecirc;ncia legal ou se razoavelmente necess&aacute;rio para: cumprir com o devido processo legal, fazer cumprir os Termos de Uso, responder a alega&ccedil;&otilde;es de suposta viola&ccedil;&atilde;o de direitos de terceiros e de divulga&ccedil;&atilde;o indevida de informa&ccedil;&otilde;es para contato de terceiros e para proteger direitos, a propriedade ou a seguran&ccedil;a de terceiros ou da pr&oacute;pria PIP Online e de seus Usu&aacute;rios.<br /> Para melhorar os Servi&ccedil;os e proteger a privacidade e as Informa&ccedil;&otilde;es Pessoais do Usu&aacute;rio, n&oacute;s podemos utilizar os Dados do Usu&aacute;rio para determinar se Voc&ecirc; est&aacute; obedecendo ou n&atilde;o a esta Pol&iacute;tica e aos Termos de Uso aplic&aacute;veis.<br /> N&oacute;s podemos utilizar m&eacute;todos tecnol&oacute;gicos automatizados para identificar, entre as mensagens trocadas entre Voc&ecirc; e o outro usu&aacute;rio, eventuais informa&ccedil;&otilde;es que possam violar ou trazer qualquer suspeita de viola&ccedil;&atilde;o aos Termos de Uso ou &agrave; legisla&ccedil;&atilde;o vigente. A identifica&ccedil;&atilde;o a que se refere esta cl&aacute;usula ser&aacute; feita exclusivamente por meio de ferramentas tecnol&oacute;gicas automatizadas, n&atilde;o havendo, em regra, qualquer acesso humano &agrave;s mensagens, ressalvadas as hip&oacute;teses estritamente necess&aacute;rias previstas nos Termos de Uso aplic&aacute;veis e na legisla&ccedil;&atilde;o vigente. N&atilde;o obstante, poder&aacute; haver o acesso a tais Mensagens pelo PIP Online quando esta for obrigada por lei ou ordem judicial a interceptar as Mensagens. Ademais, em caso de den&uacute;ncia, por outro usu&aacute;rio que estiver trocando Mensagens com Voc&ecirc; ("Denunciante"), de condutas suas em viola&ccedil;&atilde;o ou com ind&iacute;cios de viola&ccedil;&atilde;o aos Termos de Uso &agrave; legisla&ccedil;&atilde;o, o Denunciante poder&aacute;, voluntariamente e por op&ccedil;&atilde;o pr&oacute;pria dele Denunciante, divulgar referida comunica&ccedil;&atilde;o ao PIP Online.<br /> O Usu&aacute;rio declara desde j&aacute; estar ciente que o PIP Online n&atilde;o assume nenhuma responsabilidade em caso de roubo, perda, altera&ccedil;&atilde;o ou uso indevido de suas informa&ccedil;&otilde;es pessoais e dos conte&uacute;dos disponibilizados no Site.</p>
        </div>
        <h4 class="ui dividing header"><a name="p5">5. Compartilhamento da informa&ccedil;&atilde;o</a></h4>
        <div class="ui tertiary segment">
            <p>N&oacute;s n&atilde;o alugamos ou vendemos Dados dos Usu&aacute;rios a terceiros n&atilde;o afiliados, ao menos que tenhamos permiss&atilde;o espec&iacute;fica dos Nossos Usu&aacute;rios para faz&ecirc;-lo. No caso de o Nosso neg&oacute;cio ou uma divis&atilde;o do Nosso neg&oacute;cio ser reorganizado ou vendido e n&oacute;s transferirmos todos ou substancialmente todos os nossos ativos a um novo propriet&aacute;rio, sua informa&ccedil;&atilde;o pessoal pode ser transferida ao comprador independentemente de sua autoriza&ccedil;&atilde;o para garantir a continuidade do Servi&ccedil;o.<br /> N&oacute;s n&atilde;o compartilhamos Dados dos Usu&aacute;rios com partes n&atilde;o afiliadas, a menos que tenhamos autoriza&ccedil;&atilde;o espec&iacute;fica dos nossos Usu&aacute;rios para faz&ecirc;-lo, ou nas circunst&acirc;ncias abaixo:<br /> Nos reservamos o direito de compartilhar informa&ccedil;&atilde;o com autoridades p&uacute;blicas ou privadas que nos permitam lutar contra fraude e abuso em Nossa rede, investigar suspeitas de viola&ccedil;&atilde;o da lei, ou combater qualquer outra suspeita de descumprimento dos nossos Termos de Uso ou da lei;<br /> N&oacute;s podemos compartilhar informa&ccedil;&otilde;es pessoais com autoridades governamentais quando requerido de acordo com a lei aplic&aacute;vel.</p>
        </div>
        <h4 class="ui dividing header"><a name="p6">6. Controle do usu&aacute;rio</a></h4>
        <div class="ui tertiary segment">
            <p>6.1 Acesso, corre&ccedil;&atilde;o e exclus&atilde;o:<br /> Se voc&ecirc; &eacute; um Usu&aacute;rio que criou uma conta ou um an&uacute;ncio conosco, Voc&ecirc; pode acessar, requerer uma corre&ccedil;&atilde;o ou a exclus&atilde;o da informa&ccedil;&atilde;o que Voc&ecirc; forneceu enviando um e-mail para nosso canal de atendimento (acess&iacute;vel em https://www.pipbeta.com.br/fale-conosco) ou acessando o menu "Meu PIP" no nosso Site. &Eacute; importante esclarecer que o tipo de pessoa f&iacute;sica ou jur&iacute;dica e CPF informados n&atilde;o podem ser alterados, sendo permitido cadastrar apenas um e-mail para cada conta. Voc&ecirc; &eacute; respons&aacute;vel pela corre&ccedil;&atilde;o dos dados que Voc&ecirc; forneceu ou publicou em nosso Site, bem como por mant&ecirc;-los atualizados.</p>
            <p>6.2 Cookies:<br /> A maioria dos navegadores de computadores e dispositivos m&oacute;veis (como Safari, Firefox, Internet Explorer, Chrome, Opera) oferecem controles que permitem que Voc&ecirc; limite ou bloqueie a instala&ccedil;&atilde;o de cookies em seu sistema. Note que se Voc&ecirc; desabilitar os cookies no seu navegador, tanto cookies pr&oacute;prios (sites que voc&ecirc; visitou) quanto cookies de terceiros (outras empresas al&eacute;m daquelas que voc&ecirc; visitou diretamente na internet), pode haver uma piora na funcionalidade de algumas ferramentas.</p>
            <p>6.3 Coleta de bloco de dados:<br /> Se voc&ecirc; deseja limitar as informa&ccedil;&otilde;es que N&oacute;s podemos coletar/armazenar sobre Voc&ecirc;, Voc&ecirc; pode acessar a se&ccedil;&atilde;o 'Minha Conta' do Nosso Site e editar as informa&ccedil;&otilde;es fornecidas. &Eacute; importante esclarecer que o tipo de pessoa f&iacute;sica ou jur&iacute;dica e CPF informados n&atilde;o podem ser alterados, sendo permitido cadastrar apenas um e-mail para cada conta. Note ainda que algumas informa&ccedil;&otilde;es s&atilde;o necess&aacute;rias e obrigat&oacute;rias para viabilizar a utiliza&ccedil;&atilde;o do Site e que, ao excluir ou bloquear certas informa&ccedil;&otilde;es que Voc&ecirc; forneceu, seu uso dos Sites e Servi&ccedil;os pode ter uma queda da funcionalidade em alguns casos.</p>
        </div>
        <h4 class="ui dividing header"><a name="p7">7. Seguran&ccedil;a</a></h4>
        <div class="ui tertiary segment">
            <p>Toda informa&ccedil;&atilde;o que N&oacute;s coletamos &eacute; protegida por meios t&eacute;cnicos e procedimentos de seguran&ccedil;a razo&aacute;veis no intuito de evitar acessos ou uso dos dados de forma n&atilde;o autorizada.</p>
        </div>
        <h4 class="ui dividing header"><a name="p8">8. Mudan&ccedil;as nesta pol&iacute;tica</a></h4>
        <div class="ui tertiary segment">
            <p>Esta pol&iacute;tica foi atualizada em Mar&ccedil;o de 2018. N&oacute;s podemos atualizar esta Pol&iacute;tica periodicamente, cabendo ao Usu&aacute;rio verificar a vers&atilde;o mais atual no momento da utiliza&ccedil;&atilde;o dos Sites. Ao continuar utilizando nossos Servi&ccedil;os, Voc&ecirc; confirma sua aceita&ccedil;&atilde;o a quaisquer atualiza&ccedil;&otilde;es a esta Pol&iacute;tica.<br /> Se n&oacute;s fizermos altera&ccedil;&otilde;es materiais a esta Pol&iacute;tica com as quais voc&ecirc; n&atilde;o deseja concordar, Voc&ecirc; poder&aacute; descontinuar o uso dos Servi&ccedil;os.</p>
        </div>
        <h4 class="ui dividing header"><a name="p9">9. Contato</a></h4>
        <div class="ui tertiary segment">
            <p>Perguntas sobre esta pol&iacute;tica podem ser direcionadas ao e-mail privacidade@pipbeta.com.br</p>
        </div>
    </div>
</div>

